var data = [
    {
        "timestamp": "2017-05-01T18:43:45.112Z",
        "yourName": "kimJongUn",
        "walterWhite": "I would refuse to work with this person, due to THEIR TECHNICAL ABILITIES",
        "stephenColbert": "I would refuse to work with this person, due to THEIR TECHNICAL ABILITIES",
        "albertEinstein": "I would especially enjoy working with this person.",
        "rickSanchez": "I would especially enjoy working with this person.",
        "donaldTrump": "I would especially enjoy working with this person.",
        "hannahMontana": "I would especially enjoy working with this person.",
        "georgeWashington": "I would especially enjoy working with this person.",
        "pikachu": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "louisCk": "I would refuse to work with this person, due to THEIR TECHNICAL ABILITIES"
    },
    {
        "timestamp": "2017-05-01T18:44:28.417Z",
        "yourName": "borat",
        "walterWhite": "I would especially enjoy working with this person.",
        "arthurDent": "I would especially enjoy working with this person.",
        "danielBoone": "I would especially enjoy working with this person.",
        "albertEinstein": "I would especially enjoy working with this person.",
        "rickSanchez": "I would especially enjoy working with this person.",
        "sterlingArcher": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "donaldTrump": "I would especially enjoy working with this person.",
        "homerSimpson": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "kimJongUn": "I would refuse to work with this person, due to THEIR TECHNICAL ABILITIES",
        "billNyeTheScienceGuy": "I would especially enjoy working with this person.",
        "hannahMontana": "I would especially enjoy working with this person.",
        "georgeWashington": "I would especially enjoy working with this person.",
        "pikachu": "I would especially enjoy working with this person.",
        "bruceWayne": "I would especially enjoy working with this person.",
        "louisCk": "I would especially enjoy working with this person.",
        "kanyeWest": "I would especially enjoy working with this person.",
        "elsa": "I would especially enjoy working with this person."
    },
    {
        "timestamp": "2017-05-01T18:45:36.859Z",
        "yourName": "michaelScott",
        "stephenColbert": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "albertEinstein": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "spongeBob": "I would especially enjoy working with this person.",
        "sterlingArcher": "I would especially enjoy working with this person.",
        "donaldTrump": "I would especially enjoy working with this person.",
        "kimJongUn": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "billNyeTheScienceGuy": "I would especially enjoy working with this person.",
        "bojackHorseman": "I would especially enjoy working with this person.",
        "borat": "I would especially enjoy working with this person."
    },
    {
        "timestamp": "2017-05-01T18:46:19.207Z",
        "yourName": "wonderWoman",
        "walterWhite": "I would especially enjoy working with this person.",
        "albertEinstein": "I would especially enjoy working with this person.",
        "donaldTrump": "I would refuse to work with this person, due to THEIR TECHNICAL ABILITIES, I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "kimJongUn": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES"
    },
    {
        "timestamp": "2017-05-01T18:46:19.899Z",
        "yourName": "danielBoone",
        "kimJongUn": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "jeanLucPicard": "I would especially enjoy working with this person.",
        "georgeWashington": "I would especially enjoy working with this person.",
        "frodo": "I would especially enjoy working with this person."
    },
    {
        "timestamp": "2017-05-01T18:46:30.923Z",
        "yourName": "courageTheCowardlyDog",
        "rickSanchez": "I would especially enjoy working with this person.",
        "spongeBob": "I would especially enjoy working with this person.",
        "sterlingArcher": "I would especially enjoy working with this person.",
        "hobbes": "I would especially enjoy working with this person.",
        "homerSimpson": "I would especially enjoy working with this person.",
        "pikachu": "I would especially enjoy working with this person.",
        "bojackHorseman": "I would especially enjoy working with this person.",
        "bugsBunny": "I would especially enjoy working with this person.",
        "bruceWayne": "I would especially enjoy working with this person.",
        "superman": "I would especially enjoy working with this person.",
        "borat": "I would refuse to work with this person, due to THEIR TECHNICAL ABILITIES, I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "pinky": "I would especially enjoy working with this person.",
        "wonderWoman": "I would especially enjoy working with this person.",
        "heman": "I would especially enjoy working with this person."
    },
    {
        "timestamp": "2017-05-01T18:46:34.137Z",
        "yourName": "pinky",
        "walterWhite": "I would especially enjoy working with this person.",
        "arthurDent": "I would especially enjoy working with this person.",
        "danielBoone": "I would especially enjoy working with this person.",
        "stephenColbert": "I would especially enjoy working with this person.",
        "albertEinstein": "I would especially enjoy working with this person.",
        "rickSanchez": "I would especially enjoy working with this person.",
        "spongeBob": "I would especially enjoy working with this person.",
        "sterlingArcher": "I would especially enjoy working with this person.",
        "hobbes": "I would especially enjoy working with this person.",
        "donaldTrump": "I would especially enjoy working with this person.",
        "homerSimpson": "I would especially enjoy working with this person.",
        "kimJongUn": "I would especially enjoy working with this person.",
        "michaelScott": "I would especially enjoy working with this person.",
        "billNyeTheScienceGuy": "I would especially enjoy working with this person.",
        "jeanLucPicard": "I would especially enjoy working with this person.",
        "hannahMontana": "I would especially enjoy working with this person.",
        "georgeWashington": "I would especially enjoy working with this person.",
        "pikachu": "I would especially enjoy working with this person.",
        "bojackHorseman": "I would especially enjoy working with this person.",
        "bugsBunny": "I would especially enjoy working with this person.",
        "bruceWayne": "I would especially enjoy working with this person.",
        "superman": "I would especially enjoy working with this person.",
        "borat": "I would especially enjoy working with this person.",
        "pinky": "I would especially enjoy working with this person.",
        "louisCk": "I would especially enjoy working with this person.",
        "frodo": "I would especially enjoy working with this person.",
        "courageTheCowardlyDog": "I would especially enjoy working with this person.",
        "wonderWoman": "I would especially enjoy working with this person.",
        "albusPercivalWulfricBrianDumbledore": "I would especially enjoy working with this person.",
        "kanyeWest": "I would especially enjoy working with this person.",
        "elsa": "I would especially enjoy working with this person.",
        "rickGrimes": "I would especially enjoy working with this person.",
        "heman": "I would especially enjoy working with this person."
    },
    {
        "timestamp": "2017-05-01T18:46:37.716Z",
        "yourName": "frodo",
        "walterWhite": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "donaldTrump": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "kimJongUn": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "jeanLucPicard": "I would especially enjoy working with this person.",
        "georgeWashington": "I would especially enjoy working with this person.",
        "courageTheCowardlyDog": "I would especially enjoy working with this person.",
        "albusPercivalWulfricBrianDumbledore": "I would especially enjoy working with this person."
    },
    {
        "timestamp": "2017-05-01T18:46:56.896Z",
        "yourName": "sterlingArcher",
        "danielBoone": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "albertEinstein": "I would especially enjoy working with this person.",
        "donaldTrump": "I would refuse to work with this person, due to THEIR TECHNICAL ABILITIES",
        "billNyeTheScienceGuy": "I would especially enjoy working with this person.",
        "pinky": "I would especially enjoy working with this person."
    },
    {
        "timestamp": "2017-05-01T18:47:51.217Z",
        "yourName": "hannahMontana",
        "danielBoone": "I would especially enjoy working with this person.",
        "stephenColbert": "I would especially enjoy working with this person.",
        "albertEinstein": "I would especially enjoy working with this person.",
        "rickSanchez": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "spongeBob": "I would especially enjoy working with this person.",
        "sterlingArcher": "I would refuse to work with this person, due to THEIR TECHNICAL ABILITIES",
        "hobbes": "I would especially enjoy working with this person.",
        "billNyeTheScienceGuy": "I would especially enjoy working with this person.",
        "georgeWashington": "I would especially enjoy working with this person.",
        "superman": "I would especially enjoy working with this person.",
        "pinky": "I would especially enjoy working with this person.",
        "elsa": "I would especially enjoy working with this person."
    },
    {
        "timestamp": "2017-05-01T18:48:11.512Z",
        "yourName": "louisCk",
        "stephenColbert": "I would especially enjoy working with this person.",
        "donaldTrump": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "kimJongUn": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "billNyeTheScienceGuy": "I would especially enjoy working with this person.",
        "louisCk": "I would especially enjoy working with this person."
    },
    {
        "timestamp": "2017-05-01T18:48:14.724Z",
        "yourName": "superman",
        "walterWhite": "I would especially enjoy working with this person.",
        "danielBoone": "I would refuse to work with this person, due to THEIR TECHNICAL ABILITIES",
        "pinky": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "wonderWoman": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "kanyeWest": "I would especially enjoy working with this person.",
        "elsa": "I would especially enjoy working with this person.",
        "rickGrimes": "I would especially enjoy working with this person.",
        "heman": "I would especially enjoy working with this person."
    },
    {
        "timestamp": "2017-05-01T18:49:30.640Z",
        "yourName": "arthurDent",
        "walterWhite": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "danielBoone": "I would especially enjoy working with this person.",
        "albertEinstein": "I would especially enjoy working with this person.",
        "donaldTrump": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "kimJongUn": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "billNyeTheScienceGuy": "I would especially enjoy working with this person.",
        "jeanLucPicard": "I would especially enjoy working with this person.",
        "superman": "I would especially enjoy working with this person.",
        "louisCk": "I would especially enjoy working with this person."
    },
    {
        "timestamp": "2017-05-01T18:50:06.854Z",
        "yourName": "stephenColbert",
        "walterWhite": "I would especially enjoy working with this person.",
        "albertEinstein": "I would especially enjoy working with this person.",
        "spongeBob": "I would refuse to work with this person, due to THEIR TECHNICAL ABILITIES",
        "donaldTrump": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "kimJongUn": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "billNyeTheScienceGuy": "I would especially enjoy working with this person."
    },
    {
        "timestamp": "2017-05-01T18:51:30.356Z",
        "yourName": "billNyeTheScienceGuy",
        "albertEinstein": "I would especially enjoy working with this person.",
        "rickSanchez": "I would especially enjoy working with this person.",
        "donaldTrump": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "jeanLucPicard": "I would especially enjoy working with this person.",
        "albusPercivalWulfricBrianDumbledore": "I would especially enjoy working with this person."
    },
    {
        "timestamp": "2017-05-01T18:51:48.578Z",
        "yourName": "elsa",
        "donaldTrump": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "kimJongUn": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "michaelScott": "I would refuse to work with this person, due to THEIR TECHNICAL ABILITIES",
        "hannahMontana": "I would especially enjoy working with this person.",
        "georgeWashington": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "pikachu": "I would especially enjoy working with this person.",
        "bugsBunny": "I would refuse to work with this person, due to THEIR TECHNICAL ABILITIES",
        "superman": "I would especially enjoy working with this person.",
        "pinky": "I would refuse to work with this person, due to THEIR TECHNICAL ABILITIES",
        "frodo": "I would especially enjoy working with this person.",
        "wonderWoman": "I would especially enjoy working with this person.",
        "albusPercivalWulfricBrianDumbledore": "I would especially enjoy working with this person.",
        "heman": "I would especially enjoy working with this person."
    },
    {
        "timestamp": "2017-05-01T18:51:53.994Z",
        "yourName": "rickSanchez",
        "albertEinstein": "I would refuse to work with this person, due to THEIR TECHNICAL ABILITIES",
        "homerSimpson": "I would especially enjoy working with this person.",
        "michaelScott": "I would especially enjoy working with this person.",
        "georgeWashington": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "pinky": "I would especially enjoy working with this person.",
        "albusPercivalWulfricBrianDumbledore": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES"
    },
    {
        "timestamp": "2017-05-01T18:51:57.185Z",
        "yourName": "heman",
        "walterWhite": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "arthurDent": "I would especially enjoy working with this person.",
        "danielBoone": "I would especially enjoy working with this person.",
        "stephenColbert": "I would especially enjoy working with this person.",
        "rickSanchez": "I would especially enjoy working with this person."
    },
    {
        "timestamp": "2017-05-01T18:52:02.641Z",
        "yourName": "albertEinstein",
        "danielBoone": "I would especially enjoy working with this person.",
        "albertEinstein": "I would especially enjoy working with this person.",
        "kimJongUn": "I would refuse to work with this person, due to THEIR TECHNICAL ABILITIES",
        "billNyeTheScienceGuy": "I would especially enjoy working with this person.",
        "bojackHorseman": "I would refuse to work with this person, due to THEIR TECHNICAL ABILITIES",
        "borat": "I would refuse to work with this person, due to THEIR TECHNICAL ABILITIES"
    },
    {
        "timestamp": "2017-05-01T18:53:22.711Z",
        "yourName": "rickGrimes",
        "walterWhite": "I would especially enjoy working with this person.",
        "arthurDent": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "danielBoone": "I would refuse to work with this person, due to THEIR TECHNICAL ABILITIES",
        "stephenColbert": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "albertEinstein": "I would especially enjoy working with this person.",
        "rickSanchez": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "spongeBob": "I would especially enjoy working with this person.",
        "sterlingArcher": "I would especially enjoy working with this person.",
        "hobbes": "I would refuse to work with this person, due to THEIR TECHNICAL ABILITIES",
        "donaldTrump": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "homerSimpson": "I would especially enjoy working with this person.",
        "kimJongUn": "I would especially enjoy working with this person.",
        "michaelScott": "I would especially enjoy working with this person.",
        "billNyeTheScienceGuy": "I would especially enjoy working with this person.",
        "jeanLucPicard": "I would especially enjoy working with this person.",
        "hannahMontana": "I would refuse to work with this person, due to THEIR TECHNICAL ABILITIES",
        "georgeWashington": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "pikachu": "I would especially enjoy working with this person.",
        "bojackHorseman": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "bugsBunny": "I would refuse to work with this person, due to THEIR TECHNICAL ABILITIES",
        "bruceWayne": "I would refuse to work with this person, due to THEIR TECHNICAL ABILITIES",
        "superman": "I would especially enjoy working with this person.",
        "borat": "I would especially enjoy working with this person.",
        "louisCk": "I would refuse to work with this person, due to THEIR TECHNICAL ABILITIES",
        "frodo": "I would especially enjoy working with this person.",
        "courageTheCowardlyDog": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "wonderWoman": "I would especially enjoy working with this person.",
        "albusPercivalWulfricBrianDumbledore": "I would refuse to work with this person, due to THEIR TECHNICAL ABILITIES",
        "kanyeWest": "I would especially enjoy working with this person.",
        "elsa": "I would especially enjoy working with this person.",
        "rickGrimes": "I would especially enjoy working with this person.",
        "heman": "I would refuse to work with this person, due to THEIR TECHNICAL ABILITIES"
    },
    {
        "timestamp": "2017-05-01T18:53:39.667Z",
        "yourName": "donaldTrump",
        "walterWhite": "I would especially enjoy working with this person.",
        "stephenColbert": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "albertEinstein": "I would refuse to work with this person, due to THEIR TECHNICAL ABILITIES",
        "spongeBob": "I would especially enjoy working with this person.",
        "hobbes": "I would especially enjoy working with this person.",
        "donaldTrump": "I would especially enjoy working with this person.",
        "homerSimpson": "I would especially enjoy working with this person.",
        "kimJongUn": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "michaelScott": "I would especially enjoy working with this person.",
        "billNyeTheScienceGuy": "I would refuse to work with this person, due to THEIR TECHNICAL ABILITIES",
        "jeanLucPicard": "I would refuse to work with this person, due to THEIR TECHNICAL ABILITIES",
        "georgeWashington": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "pikachu": "I would especially enjoy working with this person.",
        "bruceWayne": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "superman": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "borat": "I would especially enjoy working with this person.",
        "pinky": "I would refuse to work with this person, due to THEIR TECHNICAL ABILITIES",
        "louisCk": "I would refuse to work with this person, due to THEIR TECHNICAL ABILITIES",
        "frodo": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "courageTheCowardlyDog": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "wonderWoman": "I would especially enjoy working with this person.",
        "albusPercivalWulfricBrianDumbledore": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "kanyeWest": "I would especially enjoy working with this person.",
        "elsa": "I would refuse to work with this person, due to THEIR TECHNICAL ABILITIES"
    },
    {
        "timestamp": "2017-05-01T18:56:17.768Z",
        "yourName": "spongeBob",
        "walterWhite": "I would especially enjoy working with this person.",
        "arthurDent": "I would especially enjoy working with this person.",
        "danielBoone": "I would especially enjoy working with this person.",
        "stephenColbert": "I would especially enjoy working with this person.",
        "albertEinstein": "I would especially enjoy working with this person.",
        "rickSanchez": "I would especially enjoy working with this person.",
        "spongeBob": "I would especially enjoy working with this person.",
        "sterlingArcher": "I would especially enjoy working with this person.",
        "hobbes": "I would especially enjoy working with this person.",
        "donaldTrump": "I would especially enjoy working with this person.",
        "homerSimpson": "I would especially enjoy working with this person.",
        "kimJongUn": "I would especially enjoy working with this person.",
        "michaelScott": "I would especially enjoy working with this person.",
        "billNyeTheScienceGuy": "I would especially enjoy working with this person.",
        "jeanLucPicard": "I would especially enjoy working with this person.",
        "hannahMontana": "I would especially enjoy working with this person.",
        "georgeWashington": "I would especially enjoy working with this person.",
        "pikachu": "I would especially enjoy working with this person.",
        "bojackHorseman": "I would especially enjoy working with this person.",
        "bugsBunny": "I would especially enjoy working with this person.",
        "bruceWayne": "I would especially enjoy working with this person.",
        "superman": "I would especially enjoy working with this person.",
        "borat": "I would especially enjoy working with this person.",
        "pinky": "I would especially enjoy working with this person.",
        "louisCk": "I would especially enjoy working with this person.",
        "frodo": "I would especially enjoy working with this person.",
        "courageTheCowardlyDog": "I would especially enjoy working with this person.",
        "wonderWoman": "I would especially enjoy working with this person.",
        "albusPercivalWulfricBrianDumbledore": "I would especially enjoy working with this person.",
        "kanyeWest": "I would especially enjoy working with this person.",
        "elsa": "I would especially enjoy working with this person.",
        "rickGrimes": "I would especially enjoy working with this person.",
        "heman": "I would especially enjoy working with this person."
    },
    {
        "timestamp": "2017-05-01T18:57:19.799Z",
        "yourName": "bojackHorseman",
        "walterWhite": "I would refuse to work with this person, due to THEIR TECHNICAL ABILITIES",
        "spongeBob": "I would especially enjoy working with this person.",
        "sterlingArcher": "I would especially enjoy working with this person.",
        "donaldTrump": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "kanyeWest": "I would especially enjoy working with this person."
    },
    {
        "timestamp": "2017-05-01T18:59:10.910Z",
        "yourName": "jeanLucPicard",
        "arthurDent": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "albertEinstein": "I would especially enjoy working with this person.",
        "rickSanchez": "I would especially enjoy working with this person.",
        "billNyeTheScienceGuy": "I would especially enjoy working with this person."
    },
    {
        "timestamp": "2017-05-01T19:05:24.592Z",
        "yourName": "georgeWashington",
        "walterWhite": "I would especially enjoy working with this person.",
        "stephenColbert": "I would especially enjoy working with this person.",
        "hobbes": "I would especially enjoy working with this person.",
        "donaldTrump": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "homerSimpson": "I would refuse to work with this person, due to THEIR TECHNICAL ABILITIES",
        "kimJongUn": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES"
    },
    {
        "timestamp": "2017-05-01T19:06:09.719Z",
        "yourName": "hobbes",
        "danielBoone": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "stephenColbert": "I would especially enjoy working with this person.",
        "albertEinstein": "I would especially enjoy working with this person.",
        "rickSanchez": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "kimJongUn": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "michaelScott": "I would especially enjoy working with this person.",
        "bruceWayne": "I would especially enjoy working with this person.",
        "superman": "I would especially enjoy working with this person.",
        "courageTheCowardlyDog": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "albusPercivalWulfricBrianDumbledore": "I would especially enjoy working with this person."
    },
    {
        "timestamp": "2017-05-01T19:06:14.225Z",
        "yourName": "pikachu",
        "stephenColbert": "I would especially enjoy working with this person.",
        "spongeBob": "I would especially enjoy working with this person.",
        "hobbes": "I would especially enjoy working with this person.",
        "donaldTrump": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "homerSimpson": "I would refuse to work with this person, due to THEIR TECHNICAL ABILITIES",
        "kimJongUn": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "michaelScott": "I would especially enjoy working with this person.",
        "bugsBunny": "I would especially enjoy working with this person.",
        "elsa": "I would especially enjoy working with this person."
    },
    {
        "timestamp": "2017-05-01T19:07:53.841Z",
        "yourName": "kanyeWest",
        "albertEinstein": "I would especially enjoy working with this person.",
        "donaldTrump": "I would especially enjoy working with this person.",
        "kimJongUn": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "kanyeWest": "I would especially enjoy working with this person."
    },
    {
        "timestamp": "2017-05-01T21:03:52.066Z",
        "yourName": "albusPercivalWulfricBrianDumbledore",
        "stephenColbert": "I would especially enjoy working with this person.",
        "albertEinstein": "I would especially enjoy working with this person.",
        "rickSanchez": "I would especially enjoy working with this person.",
        "sterlingArcher": "I would especially enjoy working with this person.",
        "hobbes": "I would especially enjoy working with this person.",
        "donaldTrump": "I would refuse to work with this person, due to OUR INTERPERSONAL ISSUES",
        "billNyeTheScienceGuy": "I would especially enjoy working with this person.",
        "jeanLucPicard": "I would especially enjoy working with this person.",
        "pikachu": "I would especially enjoy working with this person.",
        "bruceWayne": "I would especially enjoy working with this person.",
        "superman": "I would especially enjoy working with this person.",
        "frodo": "I would especially enjoy working with this person.",
        "albusPercivalWulfricBrianDumbledore": "I would especially enjoy working with this person."
    }
]

console.log(data[1]);