var data = [
    {
        "timestamp": "2017-05-01T18:43:45.112Z",
        "yourName": "kimJongUn",
        "walterWhite": -5,
        "stephenColbert": -5,
        "albertEinstein": 1,
        "rickSanchez": 1,
        "donaldTrump": 1,
        "hannahMontana": 1,
        "georgeWashington": 1,
        "pikachu": -5,
        "louisCk": -5
    },
    {
        "timestamp": "2017-05-01T18:44:28.417Z",
        "yourName": "borat",
        "walterWhite": 1,
        "arthurDent": 1,
        "danielBoone": 1,
        "albertEinstein": 1,
        "rickSanchez": 1,
        "sterlingArcher": -5,
        "donaldTrump": 1,
        "homerSimpson": -5,
        "kimJongUn": -5,
        "billNyeTheScienceGuy": 1,
        "hannahMontana": 1,
        "georgeWashington": 1,
        "pikachu": 1,
        "bruceWayne": 1,
        "louisCk": 1,
        "kanyeWest": 1,
        "elsa": 1
    },
    {
        "timestamp": "2017-05-01T18:45:36.859Z",
        "yourName": "michaelScott",
        "stephenColbert": -5,
        "albertEinstein": -5,
        "spongeBob": 1,
        "sterlingArcher": 1,
        "donaldTrump": 1,
        "kimJongUn": -5,
        "billNyeTheScienceGuy": 1,
        "bojackHorseman": 1,
        "borat": 1
    },
    {
        "timestamp": "2017-05-01T18:46:19.207Z",
        "yourName": "wonderWoman",
        "walterWhite": 1,
        "albertEinstein": 1,
        "donaldTrump": -5,
        "kimJongUn": -5
    },
    {
        "timestamp": "2017-05-01T18:46:19.899Z",
        "yourName": "danielBoone",
        "kimJongUn": -5,
        "jeanLucPicard": 1,
        "georgeWashington": 1,
        "frodo": 1
    },
    {
        "timestamp": "2017-05-01T18:46:30.923Z",
        "yourName": "courageTheCowardlyDog",
        "rickSanchez": 1,
        "spongeBob": 1,
        "sterlingArcher": 1,
        "hobbes": 1,
        "homerSimpson": 1,
        "pikachu": 1,
        "bojackHorseman": 1,
        "bugsBunny": 1,
        "bruceWayne": 1,
        "superman": 1,
        "borat": -5,
        "pinky": 1,
        "wonderWoman": 1,
        "heman": 1
    },
    {
        "timestamp": "2017-05-01T18:46:34.137Z",
        "yourName": "pinky",
        "walterWhite": 1,
        "arthurDent": 1,
        "danielBoone": 1,
        "stephenColbert": 1,
        "albertEinstein": 1,
        "rickSanchez": 1,
        "spongeBob": 1,
        "sterlingArcher": 1,
        "hobbes": 1,
        "donaldTrump": 1,
        "homerSimpson": 1,
        "kimJongUn": 1,
        "michaelScott": 1,
        "billNyeTheScienceGuy": 1,
        "jeanLucPicard": 1,
        "hannahMontana": 1,
        "georgeWashington": 1,
        "pikachu": 1,
        "bojackHorseman": 1,
        "bugsBunny": 1,
        "bruceWayne": 1,
        "superman": 1,
        "borat": 1,
        "pinky": 1,
        "louisCk": 1,
        "frodo": 1,
        "courageTheCowardlyDog": 1,
        "wonderWoman": 1,
        "albusPercivalWulfricBrianDumbledore": 1,
        "kanyeWest": 1,
        "elsa": 1,
        "rickGrimes": 1,
        "heman": 1
    },
    {
        "timestamp": "2017-05-01T18:46:37.716Z",
        "yourName": "frodo",
        "walterWhite": -5,
        "donaldTrump": -5,
        "kimJongUn": -5,
        "jeanLucPicard": 1,
        "georgeWashington": 1,
        "courageTheCowardlyDog": 1,
        "albusPercivalWulfricBrianDumbledore": 1
    },
    {
        "timestamp": "2017-05-01T18:46:56.896Z",
        "yourName": "sterlingArcher",
        "danielBoone": -5,
        "albertEinstein": 1,
        "donaldTrump": -5,
        "billNyeTheScienceGuy": 1,
        "pinky": 1
    },
    {
        "timestamp": "2017-05-01T18:47:51.217Z",
        "yourName": "hannahMontana",
        "danielBoone": 1,
        "stephenColbert": 1,
        "albertEinstein": 1,
        "rickSanchez": -5,
        "spongeBob": 1,
        "sterlingArcher": -5,
        "hobbes": 1,
        "billNyeTheScienceGuy": 1,
        "georgeWashington": 1,
        "superman": 1,
        "pinky": 1,
        "elsa": 1
    },
    {
        "timestamp": "2017-05-01T18:48:11.512Z",
        "yourName": "louisCk",
        "stephenColbert": 1,
        "donaldTrump": -5,
        "kimJongUn": -5,
        "billNyeTheScienceGuy": 1,
        "louisCk": 1
    },
    {
        "timestamp": "2017-05-01T18:48:14.724Z",
        "yourName": "superman",
        "walterWhite": 1,
        "danielBoone": -5,
        "pinky": -5,
        "wonderWoman": -5,
        "kanyeWest": 1,
        "elsa": 1,
        "rickGrimes": 1,
        "heman": 1
    },
    {
        "timestamp": "2017-05-01T18:49:30.640Z",
        "yourName": "arthurDent",
        "walterWhite": -5,
        "danielBoone": 1,
        "albertEinstein": 1,
        "donaldTrump": -5,
        "kimJongUn": -5,
        "billNyeTheScienceGuy": 1,
        "jeanLucPicard": 1,
        "superman": 1,
        "louisCk": 1
    },
    {
        "timestamp": "2017-05-01T18:50:06.854Z",
        "yourName": "stephenColbert",
        "walterWhite": 1,
        "albertEinstein": 1,
        "spongeBob": -5,
        "donaldTrump": -5,
        "kimJongUn": -5,
        "billNyeTheScienceGuy": 1
    },
    {
        "timestamp": "2017-05-01T18:51:30.356Z",
        "yourName": "billNyeTheScienceGuy",
        "albertEinstein": 1,
        "rickSanchez": 1,
        "donaldTrump": -5,
        "jeanLucPicard": 1,
        "albusPercivalWulfricBrianDumbledore": 1
    },
    {
        "timestamp": "2017-05-01T18:51:48.578Z",
        "yourName": "elsa",
        "donaldTrump": -5,
        "kimJongUn": -5,
        "michaelScott": -5,
        "hannahMontana": 1,
        "georgeWashington": -5,
        "pikachu": 1,
        "bugsBunny": -5,
        "superman": 1,
        "pinky": -5,
        "frodo": 1,
        "wonderWoman": 1,
        "albusPercivalWulfricBrianDumbledore": 1,
        "heman": 1
    },
    {
        "timestamp": "2017-05-01T18:51:53.994Z",
        "yourName": "rickSanchez",
        "albertEinstein": -5,
        "homerSimpson": 1,
        "michaelScott": 1,
        "georgeWashington": -5,
        "pinky": 1,
        "albusPercivalWulfricBrianDumbledore": -5
    },
    {
        "timestamp": "2017-05-01T18:51:57.185Z",
        "yourName": "heman",
        "walterWhite": -5,
        "arthurDent": 1,
        "danielBoone": 1,
        "stephenColbert": 1,
        "rickSanchez": 1
    },
    {
        "timestamp": "2017-05-01T18:52:02.641Z",
        "yourName": "albertEinstein",
        "danielBoone": 1,
        "albertEinstein": 1,
        "kimJongUn": -5,
        "billNyeTheScienceGuy": 1,
        "bojackHorseman": -5,
        "borat": -5
    },
    {
        "timestamp": "2017-05-01T18:53:22.711Z",
        "yourName": "rickGrimes",
        "walterWhite": 1,
        "arthurDent": -5,
        "danielBoone": -5,
        "stephenColbert": -5,
        "albertEinstein": 1,
        "rickSanchez": -5,
        "spongeBob": 1,
        "sterlingArcher": 1,
        "hobbes": -5,
        "donaldTrump": -5,
        "homerSimpson": 1,
        "kimJongUn": 1,
        "michaelScott": 1,
        "billNyeTheScienceGuy": 1,
        "jeanLucPicard": 1,
        "hannahMontana": -5,
        "georgeWashington": -5,
        "pikachu": 1,
        "bojackHorseman": -5,
        "bugsBunny": -5,
        "bruceWayne": -5,
        "superman": 1,
        "borat": 1,
        "louisCk": -5,
        "frodo": 1,
        "courageTheCowardlyDog": -5,
        "wonderWoman": 1,
        "albusPercivalWulfricBrianDumbledore": -5,
        "kanyeWest": 1,
        "elsa": 1,
        "rickGrimes": 1,
        "heman": -5
    },
    {
        "timestamp": "2017-05-01T18:53:39.667Z",
        "yourName": "donaldTrump",
        "walterWhite": 1,
        "stephenColbert": -5,
        "albertEinstein": -5,
        "spongeBob": 1,
        "hobbes": 1,
        "donaldTrump": 1,
        "homerSimpson": 1,
        "kimJongUn": -5,
        "michaelScott": 1,
        "billNyeTheScienceGuy": -5,
        "jeanLucPicard": -5,
        "georgeWashington": -5,
        "pikachu": 1,
        "bruceWayne": -5,
        "superman": -5,
        "borat": 1,
        "pinky": -5,
        "louisCk": -5,
        "frodo": -5,
        "courageTheCowardlyDog": -5,
        "wonderWoman": 1,
        "albusPercivalWulfricBrianDumbledore": -5,
        "kanyeWest": 1,
        "elsa": -5
    },
    {
        "timestamp": "2017-05-01T18:56:17.768Z",
        "yourName": "spongeBob",
        "walterWhite": 1,
        "arthurDent": 1,
        "danielBoone": 1,
        "stephenColbert": 1,
        "albertEinstein": 1,
        "rickSanchez": 1,
        "spongeBob": 1,
        "sterlingArcher": 1,
        "hobbes": 1,
        "donaldTrump": 1,
        "homerSimpson": 1,
        "kimJongUn": 1,
        "michaelScott": 1,
        "billNyeTheScienceGuy": 1,
        "jeanLucPicard": 1,
        "hannahMontana": 1,
        "georgeWashington": 1,
        "pikachu": 1,
        "bojackHorseman": 1,
        "bugsBunny": 1,
        "bruceWayne": 1,
        "superman": 1,
        "borat": 1,
        "pinky": 1,
        "louisCk": 1,
        "frodo": 1,
        "courageTheCowardlyDog": 1,
        "wonderWoman": 1,
        "albusPercivalWulfricBrianDumbledore": 1,
        "kanyeWest": 1,
        "elsa": 1,
        "rickGrimes": 1,
        "heman": 1
    },
    {
        "timestamp": "2017-05-01T18:57:19.799Z",
        "yourName": "bojackHorseman",
        "walterWhite": -5,
        "spongeBob": 1,
        "sterlingArcher": 1,
        "donaldTrump": -5,
        "kanyeWest": 1
    },
    {
        "timestamp": "2017-05-01T18:59:10.910Z",
        "yourName": "jeanLucPicard",
        "arthurDent": -5,
        "albertEinstein": 1,
        "rickSanchez": 1,
        "billNyeTheScienceGuy": 1
    },
    {
        "timestamp": "2017-05-01T19:05:24.592Z",
        "yourName": "georgeWashington",
        "walterWhite": 1,
        "stephenColbert": 1,
        "hobbes": 1,
        "donaldTrump": -5,
        "homerSimpson": -5,
        "kimJongUn": -5
    },
    {
        "timestamp": "2017-05-01T19:06:09.719Z",
        "yourName": "hobbes",
        "danielBoone": -5,
        "stephenColbert": 1,
        "albertEinstein": 1,
        "rickSanchez": -5,
        "kimJongUn": -5,
        "michaelScott": 1,
        "bruceWayne": 1,
        "superman": 1,
        "courageTheCowardlyDog": -5,
        "albusPercivalWulfricBrianDumbledore": 1
    },
    {
        "timestamp": "2017-05-01T19:06:14.225Z",
        "yourName": "pikachu",
        "stephenColbert": 1,
        "spongeBob": 1,
        "hobbes": 1,
        "donaldTrump": -5,
        "homerSimpson": -5,
        "kimJongUn": -5,
        "michaelScott": 1,
        "bugsBunny": 1,
        "elsa": 1
    },
    {
        "timestamp": "2017-05-01T19:07:53.841Z",
        "yourName": "kanyeWest",
        "albertEinstein": 1,
        "donaldTrump": 1,
        "kimJongUn": -5,
        "kanyeWest": 1
    },
    {
        "timestamp": "2017-05-01T21:03:52.066Z",
        "yourName": "albusPercivalWulfricBrianDumbledore",
        "stephenColbert": 1,
        "albertEinstein": 1,
        "rickSanchez": 1,
        "sterlingArcher": 1,
        "hobbes": 1,
        "donaldTrump": -5,
        "billNyeTheScienceGuy": 1,
        "jeanLucPicard": 1,
        "pikachu": 1,
        "bruceWayne": 1,
        "superman": 1,
        "frodo": 1,
        "albusPercivalWulfricBrianDumbledore": 1
    }
]

console.log(data[1]);